### ISSUE TITLE
php hint

### ISSUE THREAD

**Issue by vladis84** [granella/Netbeans-Darcula-Theme#2]
not visible variables.
![php](https://cloud.githubusercontent.com/assets/12462485/12703086/7fbbecae-c85b-11e5-9035-e41e24bd89a8.png)

**Comment by granella** [comment]
Hi!

This problem has been resolved and will be available in the next version of the plug-in (v1.4).

https://github.com/granella/Netbeans-Darcula-Theme#this-project-is-bundled-in-the-plugin-dracula-laf-from-the-version-13-see-19

**Comment by vladis84** [comment]
Thank you. 
Sorry for my English.
